version: "3.3"
services:
  api:
    restart: always
    build:
      context: ./
      dockerfile: server.dockerfile
    volumes:
      - ./:/src/app
      - /src/app/node_modules
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      NODE_ENV: development
      BASE_MONGO : mongo
      ROOT_APP : "http://app.publifactory.co"
    networks:
      - backend
      - frontend

  ssh_tunnel:
    build: ./.tunnel/
    networks:
      - backend
      - frontend

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend

  client_dev:
    restart: always
    ports:
      - "9001:9001"
    build:
      context: ./
      dockerfile: client.dockerfile
    volumes:
      - ./:/src/app
      - /src/app/node_modules
    environment:
      - PORT=9001
      - NODE_ENV=development
      - BASE_API=api
      - SITE_IP="35.246.243.12"
    depends_on:
      - api
    links:
      - api
    networks:
      - frontend

networks:
  backend:
  frontend:
