version: "3.7"

services:
  mongo:
    container_name: "mongo"
    image: mongo:4.1
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017
  api:
    build: .
    restart: always
    environment:
      - NODE_ENV=dev
    ports:
      - "4000:4000"
      - "9001:9001"
    depends_on:
      - "mongo"
    links:
      - "mongo"
