version: "3.7"
services:
  api:
    restart: always
    build:
      context: ./
      dockerfile: server.dockerfile
    volumes:
      - app:/src/app
      - node_modules:/src/app/node_modules
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
      - ssh_tunnel
    environment:
      WAIT_HOSTS: mongo:27017
      NODE_ENV: development
    networks:
      - backend
      - frontend

  ssh_tunnel:
    build: ./.tunnel/
    networks:
      - backend

  mongo:
    image: mongo
    restart: always
    build:
      context: ./
      dockerfile: mongo.dockerfile
    command: --smallfiles
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - ./database:/data

  client_dev:
    restart: always
    ports:
      - "9001:9001"
    build:
      context: ./
      dockerfile: client.dockerfile
    volumes:
      - app:/src/app
      - node_modules:/src/app/node_modules
    environment:
      - PORT=9001
      - NODE_ENV=development
    depends_on:
      - api
    links:
      - api
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  app:
  node_modules:
